"""Rollback-only PostgreSQL proof for project-agnostic marketing studio state.

The test reads the existing core.env internally, creates a private schema in a
single transaction, and rolls back everything.  It never uses production rows.
"""
from __future__ import annotations

import json
import itertools
import os
import re
import sys
import unittest
from pathlib import Path
from unittest import mock

try:
    import psycopg2
    import psycopg2.extras
except ImportError:  # pragma: no cover
    psycopg2 = None

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import marketing_studio_workflow as workflow


def _core_env():
    values = {}
    try:
        for raw in Path("/home/agency/.config/agency/core.env").read_text().splitlines():
            if "=" in raw and not raw.lstrip().startswith("#"):
                key, value = raw.split("=", 1)
                values[key.strip()] = value.strip().strip('"').strip("'")
    except OSError:
        return {}
    return values


def _dsn():
    env = _core_env()
    if not env.get("POSTGRES_PASSWORD"):
        return None
    return {
        "host": os.environ.get("MARKETING_FIXTURE_DB_HOST", "100.64.0.1"),
        "dbname": env.get("POSTGRES_DB", "agencyos"),
        "user": env.get("POSTGRES_USER", "agency"),
        "password": env["POSTGRES_PASSWORD"],
    }


def _migration_sql(path: Path) -> str:
    sql = path.read_text()
    return re.sub(r"(?im)^\s*(BEGIN|COMMIT);\s*$", "", sql)


@unittest.skipUnless(psycopg2 and _dsn(), "isolated PostgreSQL fixture is unavailable")
class MarketingStudioPostgresTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.conn = psycopg2.connect(**_dsn())
        cls.conn.autocommit = False
        cls.schema = "marketing_test_rollback"
        cur = cls.conn.cursor()
        cur.execute("CREATE SCHEMA %s" % cls.schema)
        cur.execute("SET search_path TO %s,public" % cls.schema)
        cur.execute("CREATE TABLE brands (id integer PRIMARY KEY, name text NOT NULL)")
        cur.execute("CREATE TABLE tasks (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type text NOT NULL, status text NOT NULL, params jsonb NOT NULL, triggered_by text)")
        cur.execute(_migration_sql(ROOT / "infra/migrations/020_marketing_studio.sql"))
        cur.execute(_migration_sql(ROOT / "infra/migrations/021_marketing_channels.sql"))
        cur.execute(_migration_sql(ROOT / "infra/migrations/024_marketing_channel_identity.sql"))
        cur.execute("INSERT INTO brands(id,name) VALUES (101,'Fixture North'),(202,'Fixture South')")
        # Keep the schema isolated for every following statement.  The final
        # transaction is rolled back and the schema is dropped with it.
        cur.execute("SET search_path TO %s,public" % cls.schema)

    @classmethod
    def tearDownClass(cls):
        cls.conn.rollback()
        cur = cls.conn.cursor()
        cur.execute("SELECT to_regnamespace(%s)", (cls.schema,))
        assert cur.fetchone()[0] is None, "rollback-only schema survived"
        cls.conn.close()

    @classmethod
    def cursor(cls):
        cur = cls.conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute("SET search_path TO %s,public" % cls.schema)
        return cur

    class _TxConnection:
        _ids = itertools.count()

        def __init__(self, conn, schema):
            self._conn, self._schema = conn, schema
            self._savepoint = "fixture_call_%s" % next(self._ids)
            conn.cursor().execute("SAVEPOINT " + self._savepoint)

        def cursor(self, *args, **kwargs):
            kwargs.setdefault("cursor_factory", psycopg2.extras.RealDictCursor)
            cur = self._conn.cursor(*args, **kwargs)
            cur.execute("SET search_path TO %s,public" % self._schema)
            return cur

        def commit(self):
            # Advance the simulated transaction boundary without committing the
            # outer fixture transaction or exposing its rows to other sessions.
            cur = self._conn.cursor()
            cur.execute("RELEASE SAVEPOINT " + self._savepoint)
            cur.execute("SAVEPOINT " + self._savepoint)

        def rollback(self):
            self._conn.cursor().execute("ROLLBACK TO SAVEPOINT " + self._savepoint)

        def close(self):
            pass

    def _dashboard_conn(self):
        return self._TxConnection(self.conn, self.schema)

    def setUp(self):
        self.cursor().execute("SAVEPOINT marketing_test")

    def tearDown(self):
        self.cursor().execute("ROLLBACK TO SAVEPOINT marketing_test")

    def test_migrations_and_brand_scoped_routes_are_rollback_only(self):
        cur = self.cursor()
        cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief) VALUES (101,'social_post','linkedin','North draft','{}') RETURNING id")
        item_id = cur.fetchone()["id"]
        import sys as _sys
        dashboard_root = ROOT.parents[0] / "agency-dashboard"
        _sys.path.insert(0, str(dashboard_root))
        import app as dashboard
        conn = self._dashboard_conn()
        with mock.patch.object(dashboard.models, "db", return_value=conn):
            client = dashboard.app.test_client()
            client.environ_base["HTTP_ORIGIN"] = "http://localhost"
            self.assertEqual(client.get(f"/brands/202/work/{item_id}").status_code, 404)
            self.assertEqual(client.post(f"/api/brands/202/work-items/{item_id}", json={"revision": 1, "action": "archive"}).status_code, 404)
            self.assertEqual(client.post(f"/api/brands/101/work-items/{item_id}", json={"revision": 0, "action": "archive"}).status_code, 409)

    def test_profile_channel_and_draft_task_preserve_brand_revision_contracts(self):
        dashboard_root = ROOT.parents[0] / "agency-dashboard"
        sys.path.insert(0, str(dashboard_root))
        import app as dashboard
        conn = self._dashboard_conn()
        with mock.patch.object(dashboard.models, "db", return_value=conn):
            client = dashboard.app.test_client()
            client.environ_base["HTTP_ORIGIN"] = "http://localhost"
            response = client.post("/api/brands/101/profile", json={"revision": 0, "profile": {"positioning": "North tools"}})
            self.assertEqual(response.status_code, 200)
            self.assertEqual(response.json["revision"], 1)
            response = client.post("/api/brands/101/channels/linkedin", json={"revision": 0, "display_name": "Fixture North", "bio": "North tools", "setup_checks": {"account_owned": True}})
            self.assertEqual(response.status_code, 200)
            self.assertFalse(response.json["verified"])
            cur = self.cursor()
            cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief) VALUES (101,'social_post','linkedin','North draft',%s) RETURNING id", (json.dumps({"approved_facts": ["North fact"]}),))
            item_id = cur.fetchone()["id"]
            response = client.post(f"/api/brands/101/work-items/{item_id}", json={"revision": 1, "action": "draft"})
            self.assertEqual(response.status_code, 200)
            cur.execute("SELECT params FROM tasks WHERE id=%s", (response.json["task_id"],))
            params = cur.fetchone()["params"]
            self.assertEqual(params["brand_id"], 101)
            self.assertEqual(params["revision"], 1)

    def test_campaign_rules_persist_exact_revision_without_recipient_transfer(self):
        import marketing_campaigns
        sys.path.insert(0, str(ROOT.parents[0] / 'agency-dashboard'))
        import app as dashboard
        cur = self.cursor()
        cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief,body,state) VALUES (101,'email_campaign','email','Fixture campaign','{}','Approved copy','ready') RETURNING id")
        item_id = cur.fetchone()['id']
        url = f'/api/brands/101/work-items/{item_id}/campaign'
        with mock.patch.object(dashboard.models, 'db', return_value=self._dashboard_conn()):
            client = dashboard.app.test_client()
            client.environ_base['HTTP_ORIGIN'] = 'http://localhost'
            policy = marketing_campaigns.default_policy()
            response = client.post(url, json={'revision': 1, 'policy': policy})
            self.assertEqual(response.status_code, 200)
            self.assertEqual(response.json['revision'], 2)
            self.assertFalse(response.json['sent'])
            self.assertEqual(client.post(url, json={'revision': 1, 'policy': policy}).status_code, 409)
            review = client.get(url)
            self.assertEqual(review.json['policy'], policy)
            self.assertFalse(review.json['dispatch_available'])
            self.assertEqual(client.get(f'/api/brands/202/work-items/{item_id}/campaign').status_code, 404)
            detail = client.get(f'/brands/101/work/{item_id}')
            self.assertEqual(detail.status_code, 200)
            self.assertIn(b'id="campaign-policy"', detail.data)
        cur.execute('SELECT revision,state,brief FROM marketing_work_items WHERE id=%s', (item_id,))
        saved = cur.fetchone()
        self.assertEqual(saved['state'], 'draft')
        self.assertEqual(saved['revision'], 2)
        self.assertEqual(saved['brief']['campaign_policy'], policy)
        cur.execute('SELECT count(*) AS n FROM tasks')
        self.assertEqual(cur.fetchone()['n'], 0)

    def test_provider_setup_verification_task_and_receipt_are_brand_scoped(self):
        import marketing_email_provider as provider
        sys.path.insert(0, str(ROOT.parents[0] / 'agency-dashboard'))
        import app as dashboard
        cur = self.cursor()
        cur.execute('ALTER TABLE brands ADD COLUMN project_id integer')
        cur.execute('CREATE TABLE projects(id integer PRIMARY KEY, local_path text, classification text, lifecycle text)')
        cur.execute("INSERT INTO projects VALUES (303,'/home/agency/core/deployden','core','active')")
        cur.execute('UPDATE brands SET project_id=303 WHERE id=101')
        cur.execute('CREATE TABLE brand_properties(brand_id integer,property_type text,value text,accessible boolean,created_at timestamptz DEFAULT now(),UNIQUE(brand_id,property_type))')
        config = {'provider': 'brevo', 'credential_ref': '/home/agency/.config/agency/fixture-email.env', 'credential_name': 'BREVO_API_KEY', 'sender_email': 'hello@fixture.example'}
        conn = self._dashboard_conn()
        url = '/api/brands/101/email-provider'
        with mock.patch.object(dashboard.models, 'db', return_value=conn):
            client = dashboard.app.test_client()
            client.environ_base['HTTP_ORIGIN'] = 'http://localhost'
            initial = client.get(url).json
            saved = client.post(url, json={'action': 'save', 'digest': initial['digest'], 'config': config})
            self.assertEqual(saved.status_code, 201)
            queued = client.post(url, json={'action': 'verify', 'digest': saved.json['digest']})
            self.assertEqual(queued.status_code, 201)
            again = client.post(url, json={'action': 'verify', 'digest': saved.json['digest']})
            self.assertEqual(again.json['task_id'], queued.json['task_id'])
            cur.execute('SELECT * FROM tasks WHERE id=%s', (queued.json['task_id'],))
            task = dict(cur.fetchone())
            evidence = {'status': 'verified', 'authenticated': True, 'sender_verified': True, 'checked_at': '2026-10-04T12:00:00+00:00', 'error': None}
            with mock.patch.object(provider, 'verify', return_value=evidence) as verify:
                result = provider.handle(task, lambda: conn)
            self.assertTrue(result['ok'])
            self.assertEqual(verify.call_args.args[0], config)
            readback = client.get(url).json
            self.assertEqual(readback['verification'], evidence)
            self.assertFalse(readback['sending_enabled'])
            self.assertEqual(client.get('/api/brands/202/email-provider').status_code, 409)

    def test_exact_campaign_approval_schedule_dispatch_and_receipt_are_isolated(self):
        from datetime import datetime, timedelta, timezone
        import marketing_campaign_adapter as adapter
        import marketing_campaign_execution as execution
        import marketing_campaigns
        sys.path.insert(0, str(ROOT.parents[0] / 'agency-dashboard'))
        import app as dashboard
        import campaign_execution_routes as routes
        cur = self.cursor()
        cur.execute('ALTER TABLE brands ADD COLUMN project_id integer')
        cur.execute('CREATE TABLE projects(id integer PRIMARY KEY,local_path text,classification text,lifecycle text)')
        cur.execute("INSERT INTO projects VALUES(303,'/home/agency/core/deployden','core','active')")
        cur.execute('UPDATE brands SET project_id=303 WHERE id=101')
        cur.execute('CREATE TABLE brand_properties(brand_id integer,property_type text,value text,accessible boolean,created_at timestamptz DEFAULT now(),UNIQUE(brand_id,property_type))')
        cur.execute(_migration_sql(ROOT / 'infra/migrations/023_marketing_campaign_runs.sql'))
        cur.execute('CREATE TABLE content_calendar(id integer,brand_id integer,title text,status text,planned_date date)')
        cur.execute('SELECT now() AS ts')
        approval_time = cur.fetchone()['ts'] - timedelta(minutes=1)
        class ApprovalClock(datetime):
            @classmethod
            def now(cls, tz=None): return approval_time
        config = {'schema_version':1,'base_url':'http://127.0.0.1:8123','credential_ref':'/home/agency/.config/agency/fixture-campaign.env','credential_name':'CAMPAIGN_ADAPTER_TOKEN'}
        brief = {'subject':'Fixture update','campaign_policy':marketing_campaigns.default_policy()}
        cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief,body,state,planned_at) VALUES(101,'email_campaign','email','Fixture update',%s,'Approved fixture copy','ready',now()) RETURNING id", (json.dumps(brief),))
        item_id = cur.fetchone()['id']
        url = f'/api/brands/101/work-items/{item_id}/campaign-execution'
        conn = self._dashboard_conn()
        calls = []
        class Source:
            @staticmethod
            def request_preview(item, saved_config, project, now):
                expected = adapter.preview_request(item, now)
                return {**{k:expected[k] for k in ('schema_version','brand_id','item_id','revision','message_digest','policy_digest')},'audience_digest':'a'*64,'source_revision':'fixture_1','eligible_count':2,'suppressed_count':1,'generated_at':approval_time.isoformat(),'expires_at':(approval_time+timedelta(hours=1)).isoformat(),'provider_ready':True}
            @staticmethod
            def receipt(contract, status):
                value={k:contract[k] for k in ('schema_version','brand_id','item_id','revision','idempotency_key','audience_digest','message_digest','policy_digest','source_revision')}
                return {**value,'status':status,'eligible_count':1,'delivered_count':1 if status=='delivered' else 0,'suppressed_count':1}
            @staticmethod
            def request_dispatch(contract, saved_config, project):
                cur.execute('SELECT state FROM marketing_campaign_runs WHERE id=%s',(run_id,))
                assert cur.fetchone()['state']=='dispatching'
                calls.append('POST')
                return Source.receipt(contract,'accepted')
            @staticmethod
            def request_receipt(contract, saved_config, project):
                calls.append('GET')
                return Source.receipt(contract,'delivered')
        with mock.patch.object(dashboard.models,'db',return_value=conn):
            client = dashboard.app.test_client();client.environ_base['HTTP_ORIGIN']='http://localhost'
            self.assertEqual(client.post(url, json={'action': 'preview', 'revision': 1}, headers={'Origin': 'https://untrusted.example'}).status_code, 403)
            cur.execute("UPDATE projects SET classification='external' WHERE id=303")
            self.assertEqual(client.get(url).status_code, 409)
            cur.execute("UPDATE projects SET classification='core' WHERE id=303")
            initial=client.get('/api/brands/101/campaign-source').json
            self.assertEqual(client.post('/api/brands/101/campaign-source',json={'digest':initial['digest'],'config':config}).status_code,201)
            queued=client.post(url,json={'action':'preview','revision':1})
            self.assertEqual(queued.status_code,201)
            cur.execute('SELECT * FROM tasks WHERE id=%s',(queued.json['task_id'],))
            result=execution.handle_preview(dict(cur.fetchone()),lambda:conn,Source)
            self.assertTrue(result['ok'], result)
            with mock.patch.object(routes,'datetime',ApprovalClock):
                payload={'revision':1,'send_at':(approval_time+timedelta(seconds=10)).isoformat()}
                review=client.post(url,json={**payload,'action':'review'})
                self.assertEqual(review.status_code,200,review.json)
                approval={**payload,'action':'approve','approval_digest':review.json['review']['approval_digest']}
                rejected=client.post(url,json={**approval,'approval_digest':'b'*64})
                self.assertEqual(rejected.status_code,409)
                approved=client.post(url,json=approval)
                self.assertEqual(approved.status_code,201,approved.json)
                run_id=approved.json['run_id']
                self.assertEqual(client.post(url,json=approval).json['run_id'],run_id)
            calendar = client.get('/calendar?brand_id=101')
            self.assertEqual(calendar.status_code, 200)
            self.assertIn(b'Approved delivery runs', calendar.data)
            self.assertIn(('href="/brands/101/work/%s"' % item_id).encode(), calendar.data)
            self.assertNotIn(b'Fixture South', calendar.data.split(b'Approved delivery runs')[1])
            self.assertEqual(execution.enqueue_due(lambda:conn)['queued'],1)
            self.assertEqual(execution.enqueue_due(lambda:conn)['queued'],0)
            cur.execute('SELECT t.* FROM tasks t JOIN marketing_campaign_runs r ON r.task_id=t.id WHERE r.id=%s',(run_id,))
            task=dict(cur.fetchone())
            self.assertEqual(execution.handle_dispatch(task,lambda:conn,Source)['status'],'accepted')
            self.assertEqual(execution.handle_dispatch(task,lambda:conn,Source)['status'],'accepted')
            self.assertEqual(calls,['POST'])
            receipt=client.post(url,json={'action':'receipt','run_id':run_id})
            self.assertEqual(receipt.status_code, 201, receipt.json)
            cur.execute('SELECT * FROM tasks WHERE id=%s',(receipt.json['task_id'],))
            self.assertEqual(execution.handle_receipt(dict(cur.fetchone()),lambda:conn,Source)['status'],'delivered')
            self.assertEqual(calls,['POST','GET'])
            self.assertEqual(client.post(f'/api/brands/202/work-items/{item_id}/campaign-execution',json={'action':'cancel','run_id':run_id}).status_code,404)
            self.assertEqual(client.post(url,json={'action':'cancel','run_id':run_id}).status_code,409)
            # Each send time is a separate exact approval. Cancellation persists
            # through duplicate approval and the scheduler never revives it.
            def approve_offset(seconds):
                with mock.patch.object(routes, 'datetime', ApprovalClock):
                    fields = {'revision': 1, 'send_at': (approval_time + timedelta(seconds=seconds)).isoformat()}
                    review = client.post(url, json={**fields, 'action': 'review'})
                    self.assertEqual(review.status_code, 200, review.json)
                    approval = {**fields, 'action': 'approve', 'approval_digest': review.json['review']['approval_digest']}
                    result = client.post(url, json=approval)
                    self.assertEqual(result.status_code, 201, result.json)
                    return result.json['run_id'], approval
            cancelled_id, cancelled_approval = approve_offset(20)
            self.assertEqual(client.post(url, json={'action': 'cancel', 'run_id': cancelled_id}).status_code, 200)
            with mock.patch.object(routes, 'datetime', ApprovalClock):
                repeated = client.post(url, json=cancelled_approval)
            self.assertEqual(repeated.json['state'], 'cancelled')
            self.assertFalse(repeated.json['scheduled'])
            self.assertEqual(execution.enqueue_due(lambda: conn)['queued'], 0)
            self.assertEqual(client.post(url, json={'action': 'receipt', 'run_id': cancelled_id}).status_code, 409)
            stale_id, _ = approve_offset(30)
            self.assertEqual(execution.enqueue_due(lambda: conn)['queued'], 1)
            cur.execute('SELECT t.* FROM tasks t JOIN marketing_campaign_runs r ON r.task_id=t.id WHERE r.id=%s', (stale_id,))
            stale_task = dict(cur.fetchone())
            cur.execute('UPDATE marketing_work_items SET revision=revision+1 WHERE id=%s', (item_id,))
            conn.commit()
            self.assertEqual(execution.handle_dispatch(stale_task, lambda: conn, Source)['status'], 'blocked')
            cur.execute('SELECT state FROM marketing_campaign_runs WHERE id=%s', (stale_id,))
            self.assertEqual(cur.fetchone()['state'], 'blocked')
            self.assertEqual(calls, ['POST', 'GET'])
        cur.execute('SELECT state,receipt FROM marketing_campaign_runs WHERE id=%s',(run_id,))
        result=cur.fetchone();self.assertEqual(result['state'],'delivered');self.assertEqual(result['receipt']['suppressed_count'],1)

    def test_static_withdrawal_route_and_worker_preserve_exact_receipt(self):
        import tempfile
        import publication_recovery, static_publisher
        from ghost_publisher import content_digest
        from publication_settings import destination_digest
        cur=self.cursor()
        cur.execute("ALTER TABLE brands ADD COLUMN project_id integer")
        cur.execute("ALTER TABLE tasks ADD COLUMN result_ref text")
        cur.execute("CREATE TABLE projects (id integer PRIMARY KEY,lifecycle text)")
        cur.execute("INSERT INTO projects VALUES (303,'active')")
        cur.execute("UPDATE brands SET project_id=303 WHERE id=101")
        cur.execute("CREATE TABLE content_items (id integer PRIMARY KEY,brand_id integer,status text,publish_task_id integer,structured jsonb,updated_at timestamptz)")
        dashboard_root=ROOT.parents[0]/'agency-dashboard'
        sys.path.insert(0,str(dashboard_root))
        import app as dashboard
        import publication_recovery_routes as routes
        with tempfile.TemporaryDirectory() as temporary:
            public_root=Path(temporary)/'publications'
            destination={'type':'static','enabled':True,'output_root':str(public_root/'101'),'base_url':'https://fixture.example/journal','brand_name':'Fixture'}
            article={'id':9,'brand_id':101,'title':'Fixture article','body':'Fixture text','content_blocks':[{'type':'prose','markdown':'Fixture text.'}],'structured':{},'project_status':'active','publication_status':'publishing'}
            with mock.patch.object(static_publisher,'PUBLICATION_ROOT',public_root):
                receipt=static_publisher.publish(article,destination,content_digest(article))
                approval={'content_item_id':9,'approved_destination':destination_digest(destination)}
                cur.execute("INSERT INTO tasks(type,status,params,triggered_by,result_ref) VALUES ('publish_content','done',%s,'fixture',%s) RETURNING id",(json.dumps(approval),json.dumps(receipt)))
                original_id=cur.fetchone()['id']
                cur.execute("INSERT INTO content_items VALUES (9,101,'published',%s,'{}',now())",(original_id,))
                conn=self._dashboard_conn()
                with mock.patch.object(dashboard.models,'db',return_value=conn),mock.patch.object(routes,'project_destination',return_value=destination):
                    client=dashboard.app.test_client();client.environ_base['HTTP_ORIGIN']='http://localhost'
                    review=client.get('/api/brands/101/content/9/withdraw')
                    self.assertEqual(review.status_code,200)
                    queued=client.post('/api/brands/101/content/9/withdraw',json=review.json['review'])
                    self.assertEqual(queued.status_code,201)
                with mock.patch.object(publication_recovery,'project_destination',return_value=destination):
                    result=publication_recovery.handle({'id':queued.json['task_id'],'params':review.json['review']},lambda:conn)
                self.assertTrue(result['ok'],result)
                self.assertFalse((public_root/'101/article/9/index.html').exists())
                cur.execute('SELECT status,publish_task_id FROM content_items WHERE id=9')
                state=cur.fetchone();self.assertEqual(state['status'],'draft');self.assertEqual(state['publish_task_id'],original_id)

    def test_worker_draft_execution_keeps_source_facts_and_revision(self):
        cur = self.cursor()
        cur.execute("INSERT INTO marketing_brand_profiles(brand_id,profile) VALUES (202,%s)", (json.dumps({"positioning": "South tools"}),))
        cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief) VALUES (202,'social_post','linkedin','South draft',%s) RETURNING id", (json.dumps({"approved_facts": ["South fact"]}),))
        item_id = cur.fetchone()["id"]
        conn = self._dashboard_conn()
        result = workflow.handle({"params": {"brand_id": 202, "item_id": item_id, "revision": 1}}, lambda: conn)
        self.assertTrue(result["ok"], result)
        cur = self.cursor()
        cur.execute("SELECT title,body,revision,brief FROM marketing_work_items WHERE id=%s AND brand_id=202", (item_id,))
        row = cur.fetchone()
        self.assertEqual(row["title"], "South draft")
        self.assertIn("South fact", row["body"])
        self.assertEqual(row["revision"], 2)
        self.assertFalse(json.loads(row["brief"] if isinstance(row["brief"], str) else json.dumps(row["brief"])).get("publish", False))


    def test_channel_identity_selection_reload_and_export_preserve_source_boundaries(self):
        import hashlib
        import io
        import tempfile
        import zipfile
        from PIL import Image
        import marketing_channel_identity as identity
        sys.path.insert(0, str(ROOT.parents[0] / 'agency-dashboard'))
        import app as dashboard

        with tempfile.TemporaryDirectory() as temporary:
            media_root = Path(temporary) / 'brands'
            owned = media_root / '101' / 'work' / 'identity-fixture'
            owned.mkdir(parents=True)
            image = owned / 'avatar.png'
            Image.new('RGB', (24, 24), '#123456').save(image)
            digest = hashlib.sha256(image.read_bytes()).hexdigest()
            brief = {'media': {'outputs': [{'path': str(image), 'mime': 'image/png',
                     'provenance': 'Synthetic fixture'}]}}
            cur = self.cursor()
            cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief,body,state) VALUES (101,'channel_setup','instagram','Identity fixture',%s,'Reviewed setup copy','ready') RETURNING id", (json.dumps(brief),))
            work_id = cur.fetchone()['id']
            full_copy = 'Fixture first post\n' + ('Long approved fixture copy. ' * 300) + 'End of fixture copy'
            cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief,body,state,planned_at) VALUES (101,'social_post','instagram','  =Launch fixture','{}',%s,'draft','2026-10-07T10:00:00Z')", (full_copy,))
            ref = {'work_id': work_id, 'source_revision': 1, 'filename': 'avatar.png', 'sha256': digest}
            payload = {'revision': 0, 'display_name': 'Fixture North', 'bio': 'North tools',
                       'setup_checks': {'account_owned': True}, 'identity_assets': {'avatar': ref}}
            conn = self._dashboard_conn()
            with mock.patch.object(identity, 'DEFAULT_ROOT', media_root), mock.patch.object(dashboard.models, 'db', return_value=conn):
                client = dashboard.app.test_client()
                client.environ_base['HTTP_ORIGIN'] = 'http://localhost'
                cur.execute('UPDATE marketing_work_items SET revision=2 WHERE id=%s', (work_id,))
                response = client.post('/api/brands/101/channels/instagram', json=payload)
                self.assertEqual(response.status_code, 409)
                cur.execute('UPDATE marketing_work_items SET revision=1 WHERE id=%s', (work_id,))
                response = client.post('/api/brands/101/channels/instagram', json=payload)
                self.assertEqual(response.status_code, 200, response.get_data(as_text=True))
                self.assertFalse(response.json['verified'])
                revision = response.json['revision']
                self.assertIsInstance(response.json['task_id'], int)
                cur.execute("SELECT identity_assets FROM marketing_channels WHERE brand_id=101 AND channel='instagram'")
                self.assertEqual(cur.fetchone()['identity_assets'], {'avatar': ref})
                cur.execute("SELECT params FROM tasks WHERE type='marketing_channel_setup' AND params->>'brand_id'='101' AND params->>'channel'='instagram' ORDER BY id DESC LIMIT 1")
                event = cur.fetchone()['params']
                self.assertEqual(event['identity_assets'], {'avatar': ref})
                self.assertNotIn('bio', event)
                image_url = '/brands/101/channels/instagram/identity/avatar'
                response = client.get(image_url)
                self.assertEqual(response.status_code, 200)
                self.assertEqual(response.data, image.read_bytes())
                self.assertEqual(response.headers['X-Content-Type-Options'], 'nosniff')
                self.assertIn('no-store', response.headers['Cache-Control'])
                self.assertEqual(client.get('/brands/202/channels/instagram/identity/avatar').status_code, 404)
                # A text revision does not change the selected immutable image.
                cur.execute('UPDATE marketing_work_items SET revision=2 WHERE id=%s', (work_id,))
                response = client.post('/api/brands/101/channels/instagram', json={
                    'revision': revision, 'display_name': 'Fixture North updated', 'bio': 'North tools',
                    'setup_checks': {'account_owned': True}})
                self.assertEqual(response.status_code, 200)
                revision = response.json['revision']
                self.assertEqual(response.json['identity_assets'], {'avatar': ref})
                self.assertEqual(client.get(image_url).status_code, 200)
                # The browser explicitly submits saved references on every save.
                response = client.post('/api/brands/101/channels/instagram', json={
                    'revision': revision, 'display_name': 'Fixture North updated',
                    'bio': 'North tools\nSecond line', 'setup_checks': {'account_owned': True},
                    'identity_assets': {'avatar': ref}})
                self.assertEqual(response.status_code, 200, response.get_data(as_text=True))
                self.assertEqual(response.json['identity_assets'], {'avatar': ref})
                response = client.get('/brands/101/channels/instagram/launch-kit')
                self.assertEqual(response.status_code, 200)
                with zipfile.ZipFile(io.BytesIO(response.data)) as archive:
                    files = archive.namelist()
                    self.assertIn('avatar.png', files)
                    self.assertEqual(archive.read('avatar.png'), image.read_bytes())
                    joined = b'\n'.join(archive.read(name) for name in files if name.endswith(('.json', '.md', '.csv'))).decode()
                    self.assertNotIn(temporary, joined)
                    self.assertIn('Fixture first post', joined)
                    self.assertIn('End of fixture copy', joined)
                    import csv
                    rows = list(csv.DictReader(io.StringIO(archive.read('drafts.csv').decode())))
                    exported = next(row for row in rows if row['kind'] == 'social_post')
                    self.assertEqual(exported['body'], full_copy)
                    self.assertTrue(exported['title'].startswith("'"))
                    self.assertTrue(exported['work_id'].isdigit())
                # Changed bytes cannot silently replace the selected identity.
                Image.new('RGB', (24, 24), '#654321').save(image)
                self.assertEqual(client.get(image_url).status_code, 404)
                self.assertEqual(client.get('/brands/101/channels/instagram/launch-kit').status_code, 409)


if __name__ == "__main__":
    unittest.main()
