"""Rollback-only PostgreSQL proof for project-agnostic marketing studio state.

The test reads the existing core.env internally, creates a private schema in a
single transaction, and rolls back everything.  It never uses production rows.
"""
from __future__ import annotations

import json
import os
import re
import sys
import unittest
from pathlib import Path
from unittest import mock

try:
    import psycopg2
    import psycopg2.extras
except ImportError:  # pragma: no cover
    psycopg2 = None

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import marketing_studio_workflow as workflow


def _core_env():
    values = {}
    try:
        for raw in Path("/home/agency/.config/agency/core.env").read_text().splitlines():
            if "=" in raw and not raw.lstrip().startswith("#"):
                key, value = raw.split("=", 1)
                values[key.strip()] = value.strip().strip('"').strip("'")
    except OSError:
        return {}
    return values


def _dsn():
    env = _core_env()
    if not env.get("POSTGRES_PASSWORD"):
        return None
    return {
        "host": os.environ.get("MARKETING_FIXTURE_DB_HOST", "100.64.0.1"),
        "dbname": env.get("POSTGRES_DB", "agencyos"),
        "user": env.get("POSTGRES_USER", "agency"),
        "password": env["POSTGRES_PASSWORD"],
    }


def _migration_sql(path: Path) -> str:
    sql = path.read_text()
    return re.sub(r"(?im)^\s*(BEGIN|COMMIT);\s*$", "", sql)


@unittest.skipUnless(psycopg2 and _dsn(), "isolated PostgreSQL fixture is unavailable")
class MarketingStudioPostgresTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.conn = psycopg2.connect(**_dsn())
        cls.conn.autocommit = False
        cls.schema = "marketing_test_rollback"
        cur = cls.conn.cursor()
        cur.execute("CREATE SCHEMA %s" % cls.schema)
        cur.execute("SET search_path TO %s,public" % cls.schema)
        cur.execute("CREATE TABLE brands (id integer PRIMARY KEY, name text NOT NULL)")
        cur.execute("CREATE TABLE tasks (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type text NOT NULL, status text NOT NULL, params jsonb NOT NULL, triggered_by text)")
        cur.execute(_migration_sql(ROOT / "infra/migrations/020_marketing_studio.sql"))
        cur.execute(_migration_sql(ROOT / "infra/migrations/021_marketing_channels.sql"))
        cur.execute("INSERT INTO brands(id,name) VALUES (101,'Fixture North'),(202,'Fixture South')")
        # Keep the schema isolated for every following statement.  The final
        # transaction is rolled back and the schema is dropped with it.
        cur.execute("SET search_path TO %s,public" % cls.schema)

    @classmethod
    def tearDownClass(cls):
        cls.conn.rollback()
        cur = cls.conn.cursor()
        cur.execute("SELECT to_regnamespace(%s)", (cls.schema,))
        assert cur.fetchone()[0] is None, "rollback-only schema survived"
        cls.conn.close()

    @classmethod
    def cursor(cls):
        cur = cls.conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute("SET search_path TO %s,public" % cls.schema)
        return cur

    class _TxConnection:
        def __init__(self, conn, schema):
            self._conn, self._schema = conn, schema

        def cursor(self, *args, **kwargs):
            kwargs.setdefault("cursor_factory", psycopg2.extras.RealDictCursor)
            cur = self._conn.cursor(*args, **kwargs)
            cur.execute("SET search_path TO %s,public" % self._schema)
            return cur

        def commit(self):
            pass

        def rollback(self):
            self._conn.rollback()

        def close(self):
            pass

    def _dashboard_conn(self):
        return self._TxConnection(self.conn, self.schema)

    def setUp(self):
        self.cursor().execute("SAVEPOINT marketing_test")

    def tearDown(self):
        self.cursor().execute("ROLLBACK TO SAVEPOINT marketing_test")

    def test_migrations_and_brand_scoped_routes_are_rollback_only(self):
        cur = self.cursor()
        cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief) VALUES (101,'social_post','linkedin','North draft','{}') RETURNING id")
        item_id = cur.fetchone()["id"]
        import sys as _sys
        dashboard_root = ROOT.parents[0] / "agency-dashboard"
        _sys.path.insert(0, str(dashboard_root))
        import app as dashboard
        conn = self._dashboard_conn()
        with mock.patch.object(dashboard.models, "db", return_value=conn):
            client = dashboard.app.test_client()
            client.environ_base["HTTP_ORIGIN"] = "http://localhost"
            self.assertEqual(client.get(f"/brands/202/work/{item_id}").status_code, 404)
            self.assertEqual(client.post(f"/api/brands/202/work-items/{item_id}", json={"revision": 1, "action": "archive"}).status_code, 404)
            self.assertEqual(client.post(f"/api/brands/101/work-items/{item_id}", json={"revision": 0, "action": "archive"}).status_code, 409)

    def test_profile_channel_and_draft_task_preserve_brand_revision_contracts(self):
        dashboard_root = ROOT.parents[0] / "agency-dashboard"
        sys.path.insert(0, str(dashboard_root))
        import app as dashboard
        conn = self._dashboard_conn()
        with mock.patch.object(dashboard.models, "db", return_value=conn):
            client = dashboard.app.test_client()
            client.environ_base["HTTP_ORIGIN"] = "http://localhost"
            response = client.post("/api/brands/101/profile", json={"revision": 0, "profile": {"positioning": "North tools"}})
            self.assertEqual(response.status_code, 200)
            self.assertEqual(response.json["revision"], 1)
            response = client.post("/api/brands/101/channels/linkedin", json={"revision": 0, "display_name": "Fixture North", "bio": "North tools", "setup_checks": {"account_owned": True}})
            self.assertEqual(response.status_code, 200)
            self.assertFalse(response.json["verified"])
            cur = self.cursor()
            cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief) VALUES (101,'social_post','linkedin','North draft',%s) RETURNING id", (json.dumps({"approved_facts": ["North fact"]}),))
            item_id = cur.fetchone()["id"]
            response = client.post(f"/api/brands/101/work-items/{item_id}", json={"revision": 1, "action": "draft"})
            self.assertEqual(response.status_code, 200)
            cur.execute("SELECT params FROM tasks WHERE id=%s", (response.json["task_id"],))
            params = cur.fetchone()["params"]
            self.assertEqual(params["brand_id"], 101)
            self.assertEqual(params["revision"], 1)

    def test_campaign_rules_persist_exact_revision_without_recipient_transfer(self):
        import marketing_campaigns
        sys.path.insert(0, str(ROOT.parents[0] / 'agency-dashboard'))
        import app as dashboard
        cur = self.cursor()
        cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief,body,state) VALUES (101,'email_campaign','email','Fixture campaign','{}','Approved copy','ready') RETURNING id")
        item_id = cur.fetchone()['id']
        url = f'/api/brands/101/work-items/{item_id}/campaign'
        with mock.patch.object(dashboard.models, 'db', return_value=self._dashboard_conn()):
            client = dashboard.app.test_client()
            client.environ_base['HTTP_ORIGIN'] = 'http://localhost'
            policy = marketing_campaigns.default_policy()
            response = client.post(url, json={'revision': 1, 'policy': policy})
            self.assertEqual(response.status_code, 200)
            self.assertEqual(response.json['revision'], 2)
            self.assertFalse(response.json['sent'])
            self.assertEqual(client.post(url, json={'revision': 1, 'policy': policy}).status_code, 409)
            review = client.get(url)
            self.assertEqual(review.json['policy'], policy)
            self.assertFalse(review.json['dispatch_available'])
            self.assertEqual(client.get(f'/api/brands/202/work-items/{item_id}/campaign').status_code, 404)
            detail = client.get(f'/brands/101/work/{item_id}')
            self.assertEqual(detail.status_code, 200)
            self.assertIn(b'id="campaign-policy"', detail.data)
        cur.execute('SELECT revision,state,brief FROM marketing_work_items WHERE id=%s', (item_id,))
        saved = cur.fetchone()
        self.assertEqual(saved['state'], 'draft')
        self.assertEqual(saved['revision'], 2)
        self.assertEqual(saved['brief']['campaign_policy'], policy)
        cur.execute('SELECT count(*) AS n FROM tasks')
        self.assertEqual(cur.fetchone()['n'], 0)

    def test_provider_setup_verification_task_and_receipt_are_brand_scoped(self):
        import marketing_email_provider as provider
        sys.path.insert(0, str(ROOT.parents[0] / 'agency-dashboard'))
        import app as dashboard
        cur = self.cursor()
        cur.execute('ALTER TABLE brands ADD COLUMN project_id integer')
        cur.execute('CREATE TABLE projects(id integer PRIMARY KEY, local_path text, classification text, lifecycle text)')
        cur.execute("INSERT INTO projects VALUES (303,'/home/agency/core/deployden','core','active')")
        cur.execute('UPDATE brands SET project_id=303 WHERE id=101')
        cur.execute('CREATE TABLE brand_properties(brand_id integer,property_type text,value text,accessible boolean,created_at timestamptz DEFAULT now(),UNIQUE(brand_id,property_type))')
        config = {'provider': 'brevo', 'credential_ref': '/home/agency/.config/agency/fixture-email.env', 'credential_name': 'BREVO_API_KEY', 'sender_email': 'hello@fixture.example'}
        conn = self._dashboard_conn()
        url = '/api/brands/101/email-provider'
        with mock.patch.object(dashboard.models, 'db', return_value=conn):
            client = dashboard.app.test_client()
            client.environ_base['HTTP_ORIGIN'] = 'http://localhost'
            initial = client.get(url).json
            saved = client.post(url, json={'action': 'save', 'digest': initial['digest'], 'config': config})
            self.assertEqual(saved.status_code, 201)
            queued = client.post(url, json={'action': 'verify', 'digest': saved.json['digest']})
            self.assertEqual(queued.status_code, 201)
            again = client.post(url, json={'action': 'verify', 'digest': saved.json['digest']})
            self.assertEqual(again.json['task_id'], queued.json['task_id'])
            cur.execute('SELECT * FROM tasks WHERE id=%s', (queued.json['task_id'],))
            task = dict(cur.fetchone())
            evidence = {'status': 'verified', 'authenticated': True, 'sender_verified': True, 'checked_at': '2026-10-04T12:00:00+00:00', 'error': None}
            with mock.patch.object(provider, 'verify', return_value=evidence) as verify:
                result = provider.handle(task, lambda: conn)
            self.assertTrue(result['ok'])
            self.assertEqual(verify.call_args.args[0], config)
            readback = client.get(url).json
            self.assertEqual(readback['verification'], evidence)
            self.assertFalse(readback['sending_enabled'])
            self.assertEqual(client.get('/api/brands/202/email-provider').status_code, 409)

    def test_static_withdrawal_route_and_worker_preserve_exact_receipt(self):
        import tempfile
        import publication_recovery, static_publisher
        from ghost_publisher import content_digest
        from publication_settings import destination_digest
        cur=self.cursor()
        cur.execute("ALTER TABLE brands ADD COLUMN project_id integer")
        cur.execute("ALTER TABLE tasks ADD COLUMN result_ref text")
        cur.execute("CREATE TABLE projects (id integer PRIMARY KEY,lifecycle text)")
        cur.execute("INSERT INTO projects VALUES (303,'active')")
        cur.execute("UPDATE brands SET project_id=303 WHERE id=101")
        cur.execute("CREATE TABLE content_items (id integer PRIMARY KEY,brand_id integer,status text,publish_task_id integer,structured jsonb,updated_at timestamptz)")
        dashboard_root=ROOT.parents[0]/'agency-dashboard'
        sys.path.insert(0,str(dashboard_root))
        import app as dashboard
        import publication_recovery_routes as routes
        with tempfile.TemporaryDirectory() as temporary:
            public_root=Path(temporary)/'publications'
            destination={'type':'static','enabled':True,'output_root':str(public_root/'101'),'base_url':'https://fixture.example/journal','brand_name':'Fixture'}
            article={'id':9,'brand_id':101,'title':'Fixture article','body':'Fixture text','content_blocks':[{'type':'prose','markdown':'Fixture text.'}],'structured':{},'project_status':'active','publication_status':'publishing'}
            with mock.patch.object(static_publisher,'PUBLICATION_ROOT',public_root):
                receipt=static_publisher.publish(article,destination,content_digest(article))
                approval={'content_item_id':9,'approved_destination':destination_digest(destination)}
                cur.execute("INSERT INTO tasks(type,status,params,triggered_by,result_ref) VALUES ('publish_content','done',%s,'fixture',%s) RETURNING id",(json.dumps(approval),json.dumps(receipt)))
                original_id=cur.fetchone()['id']
                cur.execute("INSERT INTO content_items VALUES (9,101,'published',%s,'{}',now())",(original_id,))
                conn=self._dashboard_conn()
                with mock.patch.object(dashboard.models,'db',return_value=conn),mock.patch.object(routes,'project_destination',return_value=destination):
                    client=dashboard.app.test_client();client.environ_base['HTTP_ORIGIN']='http://localhost'
                    review=client.get('/api/brands/101/content/9/withdraw')
                    self.assertEqual(review.status_code,200)
                    queued=client.post('/api/brands/101/content/9/withdraw',json=review.json['review'])
                    self.assertEqual(queued.status_code,201)
                with mock.patch.object(publication_recovery,'project_destination',return_value=destination):
                    result=publication_recovery.handle({'id':queued.json['task_id'],'params':review.json['review']},lambda:conn)
                self.assertTrue(result['ok'],result)
                self.assertFalse((public_root/'101/article/9/index.html').exists())
                cur.execute('SELECT status,publish_task_id FROM content_items WHERE id=9')
                state=cur.fetchone();self.assertEqual(state['status'],'draft');self.assertEqual(state['publish_task_id'],original_id)

    def test_worker_draft_execution_keeps_source_facts_and_revision(self):
        cur = self.cursor()
        cur.execute("INSERT INTO marketing_brand_profiles(brand_id,profile) VALUES (202,%s)", (json.dumps({"positioning": "South tools"}),))
        cur.execute("INSERT INTO marketing_work_items(brand_id,kind,channel,title,brief) VALUES (202,'social_post','linkedin','South draft',%s) RETURNING id", (json.dumps({"approved_facts": ["South fact"]}),))
        item_id = cur.fetchone()["id"]
        conn = self._dashboard_conn()
        result = workflow.handle({"params": {"brand_id": 202, "item_id": item_id, "revision": 1}}, lambda: conn)
        self.assertTrue(result["ok"], result)
        cur = self.cursor()
        cur.execute("SELECT title,body,revision,brief FROM marketing_work_items WHERE id=%s AND brand_id=202", (item_id,))
        row = cur.fetchone()
        self.assertEqual(row["title"], "South draft")
        self.assertIn("South fact", row["body"])
        self.assertEqual(row["revision"], 2)
        self.assertFalse(json.loads(row["brief"] if isinstance(row["brief"], str) else json.dumps(row["brief"])).get("publish", False))


if __name__ == "__main__":
    unittest.main()
