BEGIN;

CREATE TABLE IF NOT EXISTS marketing_assessments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id integer NOT NULL REFERENCES brands(id),
    project_id bigint NOT NULL REFERENCES projects(id),
    trigger_task_id integer NOT NULL REFERENCES tasks(id) ON DELETE RESTRICT,
    run_key text NOT NULL,
    schema_version integer NOT NULL DEFAULT 1 CHECK (schema_version >= 1),
    status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'collecting', 'synthesizing', 'ready', 'partial', 'failed', 'cancelled')),
    brief_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    brief_version integer NOT NULL DEFAULT 1 CHECK (brief_version >= 1),
    source_manifest jsonb NOT NULL DEFAULT '{}'::jsonb,
    report jsonb,
    validation jsonb,
    prior_assessment_id bigint REFERENCES marketing_assessments(id) ON DELETE SET NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT marketing_assessments_trigger_task_key UNIQUE (trigger_task_id),
    CONSTRAINT marketing_assessments_run_key_key UNIQUE (brand_id, project_id, run_key)
);

CREATE TABLE IF NOT EXISTS marketing_assessment_stages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id bigint NOT NULL REFERENCES marketing_assessments(id) ON DELETE CASCADE,
    stage_key text NOT NULL,
    task_id integer NOT NULL REFERENCES tasks(id) ON DELETE RESTRICT,
    required boolean NOT NULL DEFAULT true,
    status text NOT NULL DEFAULT 'queued',
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT marketing_assessment_stages_assessment_stage_key UNIQUE (assessment_id, stage_key),
    CONSTRAINT marketing_assessment_stages_task_key UNIQUE (task_id)
);

CREATE INDEX IF NOT EXISTS idx_marketing_assessments_brand_project_created
    ON marketing_assessments (brand_id, project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_marketing_assessments_status
    ON marketing_assessments (status, created_at);
CREATE INDEX IF NOT EXISTS idx_marketing_assessment_stages_assessment
    ON marketing_assessment_stages (assessment_id, status);

COMMIT;
