BEGIN;

-- Planning dates never authorize publication or automatic task execution.
CREATE TABLE IF NOT EXISTS content_calendar (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id integer NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
    title text NOT NULL CHECK (length(title) BETWEEN 1 AND 240),
    target_keyword text NOT NULL CHECK (length(target_keyword) BETWEEN 1 AND 200),
    audience text NOT NULL CHECK (length(audience) BETWEEN 1 AND 1000),
    hypothesis text NOT NULL CHECK (length(hypothesis) BETWEEN 1 AND 2000),
    success_metric text NOT NULL CHECK (success_metric IN ('gsc_clicks', 'ga4_users', 'ga4_key_events')),
    planned_date date NOT NULL,
    competitor_urls jsonb NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(competitor_urls) = 'array' AND jsonb_array_length(competitor_urls) <= 5),
    evidence_audit_id integer REFERENCES audits(id) ON DELETE RESTRICT,
    evidence_note text NOT NULL DEFAULT '' CHECK (length(evidence_note) <= 2000),
    status text NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'research_queued', 'cancelled')),
    task_id integer UNIQUE REFERENCES tasks(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((status = 'research_queued') = (task_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_content_calendar_brand_date
    ON content_calendar (brand_id, planned_date, id);

COMMIT;
