BEGIN;

-- Reviewable SEO cleanup plans.  Plans never authorize live writes.
CREATE TABLE IF NOT EXISTS seo_cleanup_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id integer NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
    audit_id integer REFERENCES audits(id) ON DELETE RESTRICT,
    plan_hash text NOT NULL,
    revision text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'proposed'
        CHECK (status IN ('proposed','approved','running','verified','failed','cancelled')),
    plan jsonb NOT NULL DEFAULT '{}'::jsonb,
    summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (brand_id, plan_hash)
);

CREATE TABLE IF NOT EXISTS seo_cleanup_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id bigint NOT NULL REFERENCES seo_cleanup_batches(id) ON DELETE CASCADE,
    evidence_id text NOT NULL,
    source_kind text NOT NULL CHECK (source_kind IN ('ghost_metadata','repo_redirect','review')),
    rule text NOT NULL,
    url text NOT NULL,
    destination text,
    precondition_hash text NOT NULL,
    precondition jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'proposed'
        CHECK (status IN ('proposed','approved','applied','verified','stale','rejected')),
    receipt jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (batch_id, evidence_id)
);

CREATE TABLE IF NOT EXISTS seo_cleanup_notifications (
    notification_key text PRIMARY KEY,
    batch_id bigint NOT NULL REFERENCES seo_cleanup_batches(id) ON DELETE CASCADE,
    channel text NOT NULL CHECK (channel IN ('discord')),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    sent_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- A compact queue snapshot lets the dashboard show the latest evidence-backed
-- article/help suggestions while preserving the source audit and human state.
CREATE TABLE IF NOT EXISTS growth_recommendations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id integer NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
    audit_id integer REFERENCES audits(id) ON DELETE RESTRICT,
    kind text NOT NULL CHECK (kind IN ('article','help')),
    title text NOT NULL CHECK (length(title) BETWEEN 1 AND 240),
    target_keyword text NOT NULL DEFAULT '',
    rank integer NOT NULL CHECK (rank > 0),
    rationale text NOT NULL DEFAULT '',
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'suggested'
        CHECK (status IN ('suggested','accepted','dismissed','scheduled','published')),
    human_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS growth_recommendations_latest_idx
    ON growth_recommendations (brand_id, kind, created_at DESC, rank);

COMMIT;
