BEGIN;

-- Brand-scoped, reviewable marketing drafts. planned_at is planning metadata;
-- it never authorizes a send, publish, account creation, or provider action.
CREATE TABLE IF NOT EXISTS marketing_work_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id integer NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
    kind text NOT NULL CHECK (kind IN ('strategy','social_post','email_campaign','video_brief','channel_setup')),
    channel text NOT NULL CHECK (channel IN ('website','blog','help','instagram','youtube','linkedin','facebook','x','email')),
    title text NOT NULL CHECK (length(title) BETWEEN 1 AND 240),
    brief jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(brief) = 'object'),
    body text NOT NULL DEFAULT '',
    state text NOT NULL DEFAULT 'draft' CHECK (state IN ('draft','ready','archived')),
    revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
    task_id integer REFERENCES tasks(id) ON DELETE SET NULL,
    planned_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS marketing_work_items_brand_state_idx
    ON marketing_work_items (brand_id, state, updated_at DESC);
CREATE INDEX IF NOT EXISTS marketing_work_items_planned_idx
    ON marketing_work_items (brand_id, planned_at) WHERE planned_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS marketing_brand_profiles (
    brand_id integer PRIMARY KEY REFERENCES brands(id) ON DELETE RESTRICT,
    profile jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(profile) = 'object'),
    revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMIT;
