BEGIN;

CREATE UNIQUE INDEX IF NOT EXISTS marketing_work_items_id_brand_idx
    ON marketing_work_items(id,brand_id);

CREATE TABLE IF NOT EXISTS marketing_campaign_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id integer NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
    item_id integer NOT NULL,
    revision integer NOT NULL CHECK (revision > 0),
    approval_digest char(64) NOT NULL UNIQUE CHECK (approval_digest ~ '^[0-9a-f]{64}$'),
    idempotency_key char(64) NOT NULL UNIQUE CHECK (idempotency_key ~ '^[0-9a-f]{64}$'),
    contract jsonb NOT NULL CHECK (jsonb_typeof(contract) = 'object'),
    state text NOT NULL CHECK (state IN ('approved','queued','dispatching','accepted','delivered','partial','blocked','uncertain','cancelled')),
    send_at timestamptz NOT NULL,
    task_id integer REFERENCES tasks(id) ON DELETE SET NULL,
    receipt jsonb CHECK (receipt IS NULL OR jsonb_typeof(receipt) = 'object'),
    error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT marketing_campaign_runs_item_revision_key UNIQUE (item_id, revision, approval_digest),
    CONSTRAINT marketing_campaign_runs_item_brand_fk FOREIGN KEY (item_id,brand_id)
        REFERENCES marketing_work_items(id,brand_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS marketing_campaign_runs_due_idx
    ON marketing_campaign_runs (state, send_at) WHERE state = 'approved';
CREATE INDEX IF NOT EXISTS marketing_campaign_runs_brand_idx
    ON marketing_campaign_runs (brand_id, updated_at DESC);

COMMIT;
